apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-01-24T21:13:27Z
  generation: 3
  labels:
    app: petclinic-app
  name: petclinic-app1
  namespace: default
  resourceVersion: "4773"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/petclinic-app
  uid: e4b7035d-201c-11e9-85d5-42010a8e0023
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: petclinic-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petclinic-app
    spec:
      containers:
      - image: gcr.io/gcp-test-le/spring-framework-petclinic@sha256:d7d9dca948f0a9fba1230293718f22fe6e4e7c565723c3f1bdaf7ef4ab7a36e0
        imagePullPolicy: IfNotPresent
        name: spring-framework-petclinic-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-01-24T21:13:28Z
    lastUpdateTime: 2019-01-24T21:13:57Z
    message: ReplicaSet "petclinic-app-55b8979d8d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2019-01-24T21:15:30Z
    lastUpdateTime: 2019-01-24T21:15:30Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
