apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-01-24T21:44:09Z
  generateName: petclinic-app-
  labels:
    app: petclinic-app
  name: petclinic-appv1
  namespace: default
  resourceVersion: "7417"
  selfLink: /api/v1/namespaces/default/services/petclinic-app-gzncg
  uid: 2ea39cf0-2021-11e9-85d5-42010a8e0023
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30250
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: petclinic-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.243.128.22
